In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=10000)

<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/datasets/imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/datasets/imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 

In [3]:
word_index = tf.keras.datasets.imdb.get_word_index()

In [4]:
word_index['fawn']

34701

In [5]:
# why in the world it's indexed by word?
reverse_word_index = dict([(value,key) for (key,value) in word_index.items()])

In [6]:
reverse_word_index[4]

'of'

In [7]:
reverse_word_index[1]

'the'

In [8]:
min([max(sequence) for sequence in x_train])

394

In [9]:
pd.DataFrame(x_train)

0
0      [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, ...
1      [1, 194, 1153, 194, 8255, 78, 228, 5, 6, 1463,...
2      [1, 14, 47, 8, 30, 31, 7, 4, 249, 108, 7, 4, 5...
3      [1, 4, 2, 2, 33, 2804, 4, 2040, 432, 111, 153,...
4      [1, 249, 1323, 7, 61, 113, 10, 10, 13, 1637, 1...
...                                                  ...
24995  [1, 14, 9, 6, 2758, 20, 21, 1517, 7, 2078, 5, ...
24996  [1, 4679, 2784, 299, 6, 1042, 37, 80, 81, 233,...
24997  [1, 11, 6, 230, 245, 6401, 9, 6, 1225, 446, 2,...
24998  [1, 1446, 7079, 69, 72, 3305, 13, 610, 930, 8,...
24999  [1, 17, 6, 194, 337, 7, 4, 204, 22, 45, 254, 8...

[25000 rows x 1 columns]

In [10]:
np.sum(y_train)/y_train.shape[0]

0.5

# encode fun

In [11]:
def vector_seq(seq,dim=10000):
  res = np.zeros((len(seq),dim))
  for i, seq in enumerate(seq):
    res[i,seq] = 1.
  return(res)

# encode

In [12]:
x_train_enc = vector_seq(x_train)
x_test_enc = vector_seq(x_test)

In [13]:
x_train_enc

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [14]:
x_train_enc.shape

(25000, 10000)

In [15]:
x_train_enc.dtype

dtype('float64')

we have an array of 25,000 rows and 10,000 columns. columns are words, rows are documents

In [16]:
y_train.dtype

dtype('int64')

In [17]:
type(y_train)

numpy.ndarray

In [18]:
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [19]:
y_train.dtype

dtype('float32')

In [20]:
type(y_train)

numpy.ndarray

In [24]:
np.dot((1,2),(2,3))

8

In [26]:
tf.keras.activations.relu(np.dot((1,2,3,4),(2,3,4,5)))

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [28]:
tf.keras.activations.relu(np.dot((1,2,3,4),(2,3,4,5)))

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [27]:
tf.keras.activations.relu(-5)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [29]:
tf.keras.activations.relu(5)

<tf.Tensor: shape=(), dtype=int32, numpy=5>